---
title: "Trait Model Selection"
author: "Bijan Seyednasrollah"
date: "May 17, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Model Selection for Trait Model using GJAM

The most appropriate model is selected using a model selection approach and based on the Deviance Information Criterion ([DIC](https://en.wikipedia.org/wiki/Deviance_information_criterion)) and a Bayesian score. The model with the highest score or the lowest DIC value is selected. 

### Predictors
The proposed models may consist of climatological variables (including mean winter temperature, soil moisture, hydrothermal deficit and hydrothermal surplus), soil data, topographical data (slope and aspect) and their interactions. The table below shows how different models explain the response variables throughout the dataset.

 __#__|__Predictors__|__DIC__|__xScore__|__yScore__
-|-|-|-|- 
1| temp + moisture + soil | -5.30e+33 | 139447.2 | -0.3812
2| temp + deficit  + soil | -5.72e+33 | 140171.2 | -0.1324
3| temp + surplus  + soil | -4.93e+33 | 139208.7 | -0.3965
4| temp + moisture + deficit  + soil | -7.08e+33| 140574.2 | -0.6544 
5| temp + moisture + therm + soil  |  |  |  
0|   |  |  |  
0|   |  |  |  
0|   |  |  |  
0|   |  |  |  
